config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :trainings, except: [:show]
  root 'trainings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excercise.rb
# frozen_string_literal: true

class Excercise < ApplicationRecord
  belongs_to :training, required: false

  def self.default_exercises
    Excercise.where(training_id: nil).collect { |e| [e.name] }
  end
end

app/models/training.rb
# frozen_string_literal: true

class Training < ApplicationRecord
  has_many :excercises, dependent: :destroy
  mount_uploader :cover, CoverUploader
  accepts_nested_attributes_for :excercises, allow_destroy: true
  default_scope { order(created_at: :asc) }

  validates_presence_of :name
  validates_presence_of :excercises
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/trainings_controller.rb
# frozen_string_literal: true

class TrainingsController < ApplicationController
  before_action :set_training, only: %i[show edit update destroy]

  def index
    @trainings = Training.all
  end

  def new
    @training = Training.new
  end

  def edit; end

  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to trainings_url, notice: 'Training was successfully created.' }
        format.json { render :index, status: :ok, location: trainings_url }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to trainings_url, notice: 'Training was successfully updated.' }
        format.json { render :index, status: :ok, location: trainings_url }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_training
    @training = Training.find(params[:id])
  end

  def training_params
    params.require(:training).permit(:name, :cover, :description, excercises_attributes: %i[name reps sets id _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: 'card border-danger') do
        concat(content_tag(:div, class: 'card-header bg-danger text-white') do
          concat "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:"
        end)
        concat(content_tag(:div, class: 'card-body') do
          concat(content_tag(:ul, class: 'mb-0') do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

app/helpers/trainings_helper.rb
# frozen_string_literal: true

module TrainingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Training Pal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/trainings/_excercise_fields.html.erb
<div class="nested-fields form-group">
	<div class="row">
		<div class="col-md-4">
			<%= f.label :name %>
			<%= f.select :name, Excercise.default_exercises, {}, {class: "form-control"} %>
		</div>
		<div class="col-md-2">
			<%= f.label :reps %>
			<%= f.select :reps, 1..12, {}, {class: "form-control"} %>
		</div>
		<div class="col-md-2">
			<%= f.label :sets %>
			<%= f.select :sets, 1..12, {}, {class: "form-control"} %>
		</div>
		<div class="col-md-1">
			<%= link_to_remove_association "remove excercise", f, class: "btn btn-danger", style:"margin-top: 30px;" %>
		</div>
	</div>
</div>

app/views/trainings/_form.html.erb
<%= form_with(model: training, local: true) do |form| %>
  
  <%= errors_for(@training) %>
  <%= image_tag(@training.cover.url, size: "200", alt: 'Cover', class: "img-fluid rounded mb-3 mb-md-0") if @training.cover? %>
  <div class="form-group">
    <%= form.label :cover %>
    <%= form.file_field :cover, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control"  %>
  </div>

  <%= form.fields_for :excercises do |excercise| %>
      <%= render 'excercise_fields', f: excercise %>
  <% end %>

  <div class="form-group">
    <%= link_to_add_association 'add excercise', form, :excercises, class: "btn btn-primary" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<h1 class="my-4">Trainings
  <small>Make it work!</small>
  <%= link_to 'New Training', new_training_path, class: "btn btn-primary" %>
</h1>

<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong><%= notice %></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
      
<% @trainings.each do |training| %>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag(training.cover.url, size: "200", alt: 'Cover', class: "img-fluid rounded mb-3 mb-md-0") if training.cover? %>
    </div>
    <div class="col-md-5">
      <h3><%= training.name %></h3>
      <h5>Excercises:</h5>
      <% training.excercises.each do |excercise| %>
        <li><%= excercise.name %> | Reps: <%= excercise.reps %> | Sets: <%= excercise.sets %></li>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Edit', edit_training_path(training), class: "btn btn-success" %>
      <%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
    <div class="col-md-12">
      <p><%= training.description %></p>
    </div>
  </div>
<hr>
<% end %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Back', trainings_path %>